<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<ApplicationIcon>slimeTemp.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TicTacToe</AssemblyName>
    <RootNamespace>TicTacToe</RootNamespace>
  </PropertyGroup>
	

</Project>
